### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by Knarf04** [eth-ait/motion-transformer#1]
Hi, 
I'm very interested in your paper, and have actually made my own implementation. However, its performance is not very close to your results. I'm wondering if you could release your code so that I can check my flaws.

**Comment by Knarf04** [comment]
Also, it would be nice if you could provide some pretrained models, thanks in advance.

**Comment by emreaksan** [comment]
Hey,

Our code and pre-trained models for the AMASS dataset are available now.

**Comment by Knarf04** [comment]
Thank you!
