### ISSUE TITLE
Is your model learning the hip motion?

### ISSUE THREAD

**Issue by mmahdavian** [eth-ait/motion-transformer#2]
Hi. I was wondering if your model only predict human body joint motions with respect to hip or it can actually predict hip motion too? I wanted to know which one are for the results you have provided in your paper?

Thank You

**Comment by kaufManu** [comment]
This model does not consider the root motion, if this is what you are referring to with "hip motion"? Or do you mean the motion of the two hip joints? In that case, yes, the model predicts the motion of the hip joints.
