### ISSUE TITLE
Missing "srnn_poses_25fps" file

### ISSUE THREAD

**Issue by lily2lab** [eth-ait/motion-transformer#3]
Hello, I can't file the folder "srnn_poses_25fps".  I found that I can generate by the code: motion-transformer-master/preprocessing/srnn_poses_in_euler.py. However, it raises another problem in line-117. I can not find the file "<path-to>/h3.6m/tfrecords/martinez_euler_gt_25fps{}.npz". Can you help me?

**Comment by kaufManu** [comment]
Can you check if the referenced pull request solves your issue?
