### ISSUE TITLE
About "ORIGINAL TotalCapture DATA W/ CORRESPONDING REFERENCE SMPL Poses" 

### ISSUE THREAD

**Issue by Dershus** [eth-ait/motion-transformer#4]
I downloaded the data provided by this link and executed preprocess.py, but I encountered a problem.
The Error message is 
''
File "preprocess_dip.py", line 362, in <module>
    create_windows=None)
  File "preprocess_dip.py", line 199, in process_split
    poses = np.array(data['poses'])  # shape (seq_length, 135)
KeyError: 'poses'
''
I print out the data, and I dont see anything about 'poses'
Do I need to download anything else, or is my understanding of the README incorrect?

**Comment by kaufManu** [comment]
I can't reproduce this. The `.pkl` files in the DIP version of AMASS contain a `'poses'` key. Can you share more information?
